name: Sync simon branch daily

on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add GitLab remote and fetch kernel-4.14 branch
        run: |
          git remote add upstream https://gitlab.com/simonpunk/susfs4ksu.git || true
          git fetch upstream kernel-4.14

      - name: Check for updates and sync branch
        run: |
          set -e
          new_commit=$(git rev-parse upstream/kernel-4.14)
          echo "Latest upstream commit: $new_commit"

          if git rev-parse --verify simon >/dev/null 2>&1; then
              git checkout simon
              current_simon_commit=$(git rev-parse HEAD)
          else
              git checkout -b simon upstream/kernel-4.14
              current_simon_commit=""
          fi

          if [ "$current_simon_commit" != "$new_commit" ]; then
              echo "Updating simon branch..."
              git reset --hard upstream/kernel-4.14
              git rm --cached .github/workflows/*.yml 2>/dev/null || true
              git add -A
              git commit -m "Sync simon with upstream" || echo "No changes"
              git push origin simon --force
          else
              echo "Simon branch is already up to date."
          fi

      - name: Clear older runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list -L400 --json databaseId -q '.[].databaseId' | tail -n+5 | xargs -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || :